# System for quickly and painlessly provisioning Couchbase Server virtual machines across multiple Couchbase versions and OS's.
# See README.md for usage instructions

### Variable declarations - FEEL FREE TO EDIT THESE ###
begin
ip_addresses = { 
  "ubuntu14" => 142,
  "4.1.0"    => 110
}
vagrant_boxes = {
  "ubuntu14" => "ubuntu/trusty64"
}

# Collect the names of the working directory and its parent (os and cb version)
operating_system = "ubuntu14"
version  ||= "4.1.0"

# Couchbase Server Version download links
couchbase_releases = "http://packages.couchbase.com/releases"
latest_builds = "http://latestbuilds.hq.couchbase.com"
sherlock_builds = "#{latest_builds}/couchbase-server/sherlock"
watson_builds =  "http://172.23.120.24/builds/latestbuilds/couchbase-server/watson"
couchbase_download_links = {
  "4.1.1-testing" => {
	          "centos6"    => "#{sherlock_builds}/5551/couchbase-server-enterprise-4.1.1-5551-centos6.x86_64",
	          "centos7"    => "#{sherlock_builds}/5551/couchbase-server-enterprise-4.1.1-5551-centos7.x86_64",
	          "debian7"    => "#{sherlock_builds}/5551/couchbase-server-enterprise_4.1.1-5551-debian7_amd64",
	          "debian8"    => "#{sherlock_builds}/5551/couchbase-server-enterprise_4.1.1-5551-debian7_amd64",
	          "opensuse11" => "#{sherlock_builds}/5551/couchbase-server-enterprise-4.1.1-5551-suse11.x86_64",
	          "opensuse12" => "#{sherlock_builds}/5551/couchbase-server-enterprise-4.1.1-5551-suse11.x86_64",
	          "ubuntu12"   => "#{sherlock_builds}/5551/couchbase-server-enterprise_4.1.1-5551-ubuntu12.04_amd64",
	          "ubuntu14"   => "#{sherlock_builds}/5551/couchbase-server-enterprise_4.1.1-5551-ubuntu14.04_amd64",
  },
  "4.5.0-testing" => {
              "centos6"    => "#{watson_builds}/708/couchbase-server-enterprise-4.5.0-708-centos6.x86_64",
              "centos7"    => "#{watson_builds}/708/couchbase-server-enterprise-4.5.0-708-centos7.x86_64",
              "debian7"    => "#{watson_builds}/708/couchbase-server-enterprise_4.5.0-708-debian7_amd64",
              "debian8"    => "#{watson_builds}/708/couchbase-server-enterprise_4.5.0-708-debian7_amd64",
              "opensuse11" => "#{watson_builds}/708/couchbase-server-enterprise-4.5.0-708-suse11.x86_64",
              "opensuse12" => "#{watson_builds}/708/couchbase-server-enterprise-4.5.0-708-suse11.x86_64",
              "ubuntu12"   => "#{watson_builds}/708/couchbase-server-enterprise_4.5.0-708-ubuntu12.04_amd64",
              "ubuntu14"   => "#{watson_builds}/708/couchbase-server-enterprise_4.5.0-708-ubuntu14.04_amd64",
  },
  "ubuntu14"   => "#{couchbase_releases}/#{version}/couchbase-server-enterprise_#{version}-ubuntu14.04_amd64",
}

default_number_of_nodes = 4
default_RAM_in_MB = 1024
default_number_of_cpus = 1

## Edit these to allow other machines in your network to access the VMs

# Set to true to activate non-host access
#  make sure no one else will be impacted by this, as VMs will have forced ip that could collide
#  (typically you should be close to alone on the LAN, with a few machines, ie at home)
# alternatively set use_dhcp to true to avoid this (at the cost of not knowing the IP in advance)
public_lan = false
use_dhcp = false

# Name of the host endpoint to serve as bridge to local network
#  (if not found vagrant will ask the user for each node)
default_bridge = "wlan0"

# Base for IP in public network. %d replaced by node number, eg "192.168.1.10%d" to get 101, 102, ...
#  (once again, be careful of potential ip collisions!)
public_ip_base = "192.168.1.10%d"


### DO NOT EDIT BELOW THIS LINE

# Number of nodes to provision
unless ENV['VAGRANT_NODES'].nil? || ENV['VAGRANT_NODES'] == 0
  num_nodes = ENV['VAGRANT_NODES'].to_i
else
  if num_nodes.nil?
    num_nodes = default_number_of_nodes
  end
end

unless ENV['VAGRANT_CPUS'].nil? || ENV['VAGRANT_CPUS'] == 0
  num_cpus = ENV['VAGRANT_CPUS'].to_i
else
  num_cpus = default_number_of_cpus
end

unless ENV['VAGRANT_RAM'].nil? || ENV['VAGRANT_RAM'] == 0
  ram_in_MB = ENV['VAGRANT_RAM'].to_i
else
  ram_in_MB = default_RAM_in_MB
end

unless ENV['VAGRANT_VPN'].nil?
  vpn = "on"
else
  vpn = "off"
end

# Check to see if a custom download location has been given, if not use a default value (2.5.0 style)
if couchbase_download_links.has_key?(version)
  if couchbase_download_links[version].is_a?(String)
    url = couchbase_download_links[version]
  elsif couchbase_download_links[version].has_key?(operating_system)
    url = couchbase_download_links[version][operating_system]
  end
elsif couchbase_download_links.has_key?(operating_system)
  url = couchbase_download_links[operating_system]
end
url ||= "#{couchbase_releases}/#{version}/couchbase-server-enterprise_#{version}_x86_64"

puppet_location ||= ""

# Check to see if a custom ip address has been given, if not generate one
if (defined?(ip)).nil?
  ip_address = "10." + String(ip_addresses[operating_system]) + "." + String(ip_addresses[version]) + ".10%d"
end

# Generate a hostname template
hostname = "#{version.gsub '.', ''}-#{operating_system}.vagrants"
if hostname =~ /^[0-9]/
  hostname.prepend("cb")
end
hostname.prepend("node%d-")

# Check to see if the vagrant command given was 'up', if so print a handy dialogue
if ARGV[0] == "up" && !ARGV[1]
  puts "\e[32m=== Upping #{num_nodes} node(s) on #{operating_system} and cb version #{version} ==="
end

### Start the vagrant configuration ###
Vagrant.configure("2") do |config|

  # Define VM properties for each node (for both virtualbox and
  # libvirt providers).
  config.vm.provider :virtualbox do |vb|
    vb.memory = ram_in_MB
    vb.cpus = num_cpus
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "#{vpn}"]
  end
  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = ram_in_MB
    libvirt.cpus = num_cpus
  end

  config.vm.synced_folder ENV['HOME'], "/vmhost_home/"

  # Define the vagrant box download location
  if !(vagrant_boxes[operating_system]["box_url"].nil?)
    config.vm.box_url = vagrant_boxes[operating_system]["box_url"]
  end

  # Define the vagrant box name
  if !(vagrant_boxes[operating_system]["box_name"].nil?)
    box_name = vagrant_boxes[operating_system]["box_name"]
  else
    box_name = vagrant_boxes[operating_system]
  end

  # Define the box version if specified - default to most recent
  if !(vagrant_boxes[operating_system]["box_version"].nil?)
    box_version = vagrant_boxes[operating_system]["box_version"]
  end

  # Check to see if the VM is not running Windows and provision with puppet
  if !(operating_system.include?("win"))
    # Provision the server itself with puppet
    config.vm.provision "puppet" do |puppet|
      puppet.manifests_path = puppet_location # Define a custom location and name for the puppet file
      puppet.manifest_file = "puppet.pp"
      puppet.facter = { # Pass variables to puppet
        "version" => version, # Couchbase Server version
        "url" => url, # Couchbase download location
      }
    end
  end

  # Provision Config for each of the nodes
  1.upto(num_nodes) do |num|
    config.vm.define "node#{num}" do |node|
      node.vm.box = box_name
      if !(box_version.nil?)
        node.vm.box_version = box_version
      end
      if public_lan && use_dhcp
        node.vm.network :public_network, :bridge => default_bridge
        puts "Public LAN ip obtained via DHCP, find it by connecting to the node: vagrant ssh node#{num}"
      elsif public_lan
       node.vm.network :public_network, :bridge => default_bridge, :ip =>  public_ip_base % num
       puts "Public LAN ip : #{public_ip_base % num}"
      else
        node.vm.network :private_network, :ip => ip_address % num
        if Vagrant.has_plugin?("landrush")
          puts "Private network (host only) : http://#{hostname % num}:8091/"
        else
          puts "Private network (host only) : http://#{ip_address % num}:8091/"
        end
      end
      node.vm.hostname = hostname % num
      node.vm.provider "virtualbox" do |v|
        v.name = "Couchbase Server #{version} Running On #{operating_system.gsub '/', '_'} Node #{num}"
        if(operating_system.include?("win")) # If the VM is running Windows it will start with a GUI
          v.gui = true
        end
      end
      if Vagrant.has_plugin?("landrush")
        node.landrush.enabled = true
        node.landrush.tld = "vagrants"
      end
      # Postfix a random value to hostname to uniquify it.
      node.vm.provider "libvirt" do |v|
        v.random_hostname = true
      end
    end
  end

  if ARGV[0] == "up" && !ARGV[1]
    if public_lan && use_dhcp
      puts "\e[32m=== Upping #{num_nodes} node(s) on public LAN via DHCP ==="
    elsif public_lan
      puts "\e[32m=== Upping #{num_nodes} node(s) on public LAN IPs #{public_ip_base.sub('%d','')}{1..#{num_nodes}} ==="
    else
      puts "\e[32m=== Upping #{num_nodes} node(s) on IPs #{ip_address.sub('%d','')}{1..#{num_nodes}} ==="
    end
  end

end
rescue
end
